added periodic method to indexer
FRC1732/2020-Competition pull request #19
Opened 2020-01-18 19:42 UTC by MarcusPickett

added periodic method to indexer

2020-01-18 19:53 UTC, mgottsacker34 commented on src/main/java/frc/robot/subsystems/Indexer.java
> +  }
These lines should be indented.

2020-01-21 01:21 UTC, duffym22 requested changes
See comments

2020-01-21 01:21 UTC, duffym22 commented on src/main/java/frc/robot/subsystems/Indexer.java
> +    Solenoid cellGate = new Solenoid(4);
Replace magic numbers and reference existing CAN ID constants in Constants.java

2020-01-30 03:04 UTC, borkae commented on src/main/java/frc/robot/subsystems/Indexer.java
> +    Solenoid cellGate = new Solenoid(Constants.INDEXER_CELLGATE_ID);
Add private to the class variables and move "new" operations into constructor.

2020-01-31 01:21 UTC, borkae approved these changes
Recommended changes complete.

2020-02-01 16:45 UTC, duffym22 approved these changes
Approved

2020-02-01 16:45 UTC, merged