Feature/properties
FRC1732/2020-Competition pull request #40
Opened 2020-02-07 02:51 UTC by MarcusPickett

Issue #39

2020-02-07 02:53 UTC, borkae approved these changes

2020-02-07 13:55 UTC, duffym22 approved these changes

2020-02-07 13:57 UTC, duffym22 requested changes
Uncomment the commented out lines for drivetrain (understandable it was used for testing). This way we won't have another pull request just for uncommenting out the lines

2020-02-08 17:08 UTC, borkae approved these changes

2020-02-08 19:11 UTC, duffym22 approved these changes
Approved

2020-02-08 19:49 UTC, merged