THE FUTURE IS HERE AND IT IS UNTESTED SMART SHOOTER
FRC1732/2020-Competition pull request #86
Opened 2020-02-21 02:26 UTC by SamuelStone-beep

2020-02-21 04:05 UTC, borkae requested changes

2020-02-21 04:05 UTC, borkae commented on src/main/java/frc/robot/commands/SmartShooter.java
> +  Shooter shooter;
Make these private.

2020-02-22 16:01 UTC, borkae approved these changes

2020-02-22 16:04 UTC, duffym22 approved these changes

2020-02-22 16:04 UTC, merged